### PR TITLE
Enable OpenLab periodic check

### PR DESCRIPTION
**Pull request by kiwik**
Periodic check will be triggered at UTC-0 0:00 and 12:00 of everyday
automatically, unit and acceptance tests will be executed, results will
be shown in OpenLab CI dashboard http://status.openlabtesting.org/t/openlab/builds.html

Closes theopenlab/openlab#63

### CODE REVIEW

**Comment by kiwik** [comment]
recheck

**Comment by kiwik** [comment]
recheck

**Comment by kiwik** [comment]
recheck fwaas

**Comment by kiwik** [comment]
recheck lbaas

**Comment by kiwik** [comment]
recheck

**Comment by kiwik** [comment]
recheck fwaas

**Comment by kiwik** [comment]
recheck lbaas

**Comment by kiwik** [comment]
recheck trove

**Comment by kiwik** [comment]
recheck designate

**Comment by kiwik** [comment]
recheck lbaas

**Comment by kiwik** [comment]
recheck

**Comment by kiwik** [comment]
recheck fwaas

**Comment by kiwik** [comment]
recheck lbaas

**Comment by kiwik** [comment]
recheck

**Comment by kiwik** [comment]
recheck lbaas

**Comment by kiwik** [comment]
LBaaS issue should be fixed in https://review.openstack.org/#/c/575687/

**Comment by kiwik** [comment]
recheck trove

**Comment by kiwik** [comment]
recheck trove

**Comment by kiwik** [comment]
recheck lbaas

**Comment by kiwik** [comment]
fwaas issue should be fixed in https://github.com/terraform-providers/terraform-provider-openstack/pull/344

**Comment by kiwik** [comment]
LBaaS job pip timeout

**Comment by kiwik** [comment]
recheck lbaas

**Comment by liu-sheng** [comment]
recheck lbaas

**Comment by liu-sheng** [comment]
recheck fwaas

**Comment by kiwik** [comment]
recheck lbaas

**Comment by kiwik** [comment]
recheck lbaas

**Comment by kiwik** [comment]
recheck lbaas

**Comment by kiwik** [comment]
LBaaS issue have been reported at https://github.com/terraform-providers/terraform-provider-openstack/issues/355

**Comment by kiwik** [comment]
FWaaS issue have been report at https://github.com/terraform-providers/terraform-provider-openstack/pull/344

**Comment by kiwik** [comment]
Let us to wait until all of the issues are addressed, then to merged the PR.

**Comment by kiwik** [comment]
OpenStack Octavia Bug https://storyboard.openstack.org/#!/story/2002927

**Comment by kiwik** [comment]
recheck lbaas

**Comment by kiwik** [comment]
recheck lbaas

**Comment by jtopjian** [comment]
recheck queens

**Comment by jtopjian** [comment]
recheck stable/queens

**Comment by kiwik** [comment]
recheck stable/queens

**Pull request closed without merging**
