### PR TITLE
Support acceptance test against OpenStack Rocky release in OpenLab

### PR DESCRIPTION
**Pull request by h00130372**
Input comment "recheck stable/rocky" in pull request comments, that
will trigger acceptance tests against OpenStack Rocky release. OpenLab
will report test result in followint comments automatically.

### CODE REVIEW

**Comment by h00130372** [comment]
recheck stable/rocky

**Comment by h00130372** [comment]
recheck stable/rocky

**Comment by liu-sheng** [comment]
recheck

**Comment by h00130372** [comment]
@jtopjian would you please to approve this pr later if the ci checks are all success, thank you.

**Comment by jtopjian** [comment]
Thank you for working on this :)

**Pull request merged**
