### PR TITLE
Images v2: Fix Computed Properties

### PR DESCRIPTION
**Pull request by jtopjian**
Newer versions of OpenStack are automatically setting properties
on images. This commit will reconcille the server-provided
properties with the user-provided properties.

### CODE REVIEW

**Comment by jtopjian** [comment]
recheck

**Comment by jtopjian** [comment]
I'm not sure why this test is failing consistently. It's passing for me:

```
--- PASS: TestAccComputeV2FloatingIPAssociate_attachToSecondNetwork (82.82s)
```

I'm going to launch a new Devstack environment to see if anything has changed in the past 48 hours.

**Comment by jtopjian** [comment]
recheck

**Comment by jtopjian** [comment]
I'm unable to reproduce the error in a fresh devstack environment, so it might be something with OpenLab. It might be worthwhile just to disable that test altogether.

Anyway, @fatmcgav this is ready for your review at your convenience. I'm quite happy with how this turned out.

**Comment by flaper87** [comment]
This lgtm, thanks!

**Pull request merged**
