### PR TITLE
Add ability to list availability zones for blockstorage and sharedfilesystem

### LINKED ISSUE #651: Add possibility to list available availability zones
In order when user wants to create multiple clusters bound to the availability zone, it would be great to fetch the list of availability zones as a data source.

### Affected Data Source(s)

- openstack_availability_zones

### PR DESCRIPTION
**Pull request by kayrus**
Resolves #651

### CODE REVIEW

**Comment by kayrus** [comment]
@jtopjian ready for review

**Comment by jtopjian** [comment]
There should be 3 data sources for these - one for each service.

**Comment by kayrus** [comment]
How do you suggest to call new data sources?
* openstack_compute_az
* openstack_compute_azs
* openstack_compute_availability_zones

**Comment by kayrus** [comment]
For HA deployments, scaled accross multiple regions. Some regions have different amount of AZ. For sure, they can be specified manually in a list, but if it can be automated, I'd automate it, especially when you have more than 10 regions. Do you have other thoughts?

**Comment by kayrus** [comment]
@jtopjian ready for review

**Comment by kayrus** [comment]
@jtopjian could you please take another look on this PR?

**Pull request merged**
