### PR TITLE
Migrate to the new separated SDK

### PR DESCRIPTION
**Pull request by ozerovandrei**
Remove deprecated terraform helpers to get User-Agent.

Add terraformVersion into provider config.

Migrate to terraform-plugin-sdk via tf-sdk-migrator.

Reference: https://www.terraform.io/docs/extend/plugin-sdk.html

### CODE REVIEW

**Comment by ozerovandrei** [comment]
recheck-trove

**Comment by ozerovandrei** [comment]
recheck-designate

**Comment by ozerovandrei** [comment]
recheck-lbaas

**Comment by ozerovandrei** [comment]
recheck-fwaas

**Comment by ozerovandrei** [comment]
recheck-lbaas

**Comment by ozerovandrei** [comment]
recheck lbaas

**Comment by ozerovandrei** [comment]
recheck fwaas

**Comment by ozerovandrei** [comment]
recheck designate

**Comment by ozerovandrei** [comment]
recheck trove

**Comment by ozerovandrei** [comment]
recheck lbaas

**Comment by ozerovandrei** [comment]
lbaas:
```
panic: test timed out after 2h0m0s
```

fwaas:
```
2019-09-26 10:13:03.065978 | ubuntu-xenial |         Error: Error creating openstack_fw_rule_v1: Resource not found
2019-09-26 10:13:03.066056 | ubuntu-xenial |
2019-09-26 10:13:03.066147 | ubuntu-xenial |           on /tmp/tf-test768020168/main.tf line 16:
2019-09-26 10:13:03.066203 | ubuntu-xenial |           (source code not available)
2019-09-26 10:13:03.066227 | ubuntu-xenial |
2019-09-26 10:13:03.066252 | ubuntu-xenial |
2019-09-26 10:13:03.066282 | ubuntu-xenial |
2019-09-26 10:13:03.066359 | ubuntu-xenial |         Error: Error creating openstack_fw_rule_v1: Resource not found
2019-09-26 10:13:03.066387 | ubuntu-xenial |
2019-09-26 10:13:03.066436 | ubuntu-xenial |           on /tmp/tf-test768020168/main.tf line 11:
2019-09-26 10:13:03.066492 | ubuntu-xenial |           (source code not available)
2019-09-26 10:13:03.066515 | ubuntu-xenial |
```

**Comment by ozerovandrei** [comment]
recheck fwaas

**Comment by ozerovandrei** [comment]
Also fwaas:
```
2019-09-26 18:47:32.602771 | ubuntu-xenial | 2019/09/26 18:47:32 [DEBUG] openstack_fw_policy_v1.policy_1: apply errored, but we're indicating that via the Error pointer rather than returning it: Error creating openstack_fw_policy_v1: Resource not found
2019-09-26 18:47:32.603129 | ubuntu-xenial | 2019/09/26 18:47:32 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: Error creating openstack_fw_policy_v1: Resource not found
2019-09-26 18:47:32.603487 | ubuntu-xenial | 2019/09/26 18:47:32 [ERROR] <root>: eval: *terraform.EvalSequence, err: Error creating openstack_fw_policy_v1: Resource not found
```

**Comment by jtopjian** [comment]
@ozerovandrei Yep, full testing of FWaaS is very difficult. There have been a lot of breaking API changes between releases so full testing requires running the tests on different releases and making note of which ones passed on each release.

**Comment by ozerovandrei** [comment]
recheck lbaas

**Comment by ozerovandrei** [comment]
Well, I guess that we're ready to merge this.

**Pull request merged**
