### PR TITLE
Images v2: Properties

### PR DESCRIPTION
**Pull request by jtopjian**
Partial for #89

### CODE REVIEW

**Comment by fatmcgav** [comment]
@jtopjian Code changes look sensible to me... I'll try and give it a test later...

**Comment by DSpeichert** [comment]
Something is not quite working properly for me, the debug output shows a bunch of images being received for the query and an image satisfy the property I'm asking for, yet I see:
```
* data.openstack_images_image_v2.test_image: data.openstack_images_image_v2.test_image: Your query returned no results. Please change your search criteria and try again.
```

I'll do some more debugging...

**Comment by jtopjian** [comment]
@DSpeichert Sure, sounds good. For some reason the logic of satisfying all properties threw me for a loop and I took me two or three tries until my own tests were working. It's unfortunate that the Terraform test framework does not allow testing for error cases, too.

**Comment by jtopjian** [comment]
@DSpeichert Thank you very much for testing and verifying this!

**Pull request merged**
