### PR TITLE
Networking V2: add subnetpool field to the subnet

### PR DESCRIPTION
**Pull request by ozerovandrei**
Add subnetpool field to the subnet resource and data source.

For: #242 

This PR depends on #243 PR.

### CODE REVIEW

**Comment by ozerovandrei** [comment]
Strange. It fails on `TestAccComputeV2FloatingIPAssociate_attachToSecondNetwork`.

**Comment by ozerovandrei** [comment]
recheck

**Comment by jtopjian** [comment]
> Strange. It fails on TestAccComputeV2FloatingIPAssociate_attachToSecondNetwork.

Yeah, that test randomly fails. Just do a recheck (like you did :)

**Comment by ozerovandrei** [comment]
recheck

**Comment by jtopjian** [comment]
@ozerovandrei This looks good, too! But would you mind rebasing this now that #243 has been merged? I believe this will merge successfully as-is but I want to be cautious with the vendoring.

**Comment by ozerovandrei** [comment]
@jtopjian done. Rebased it from the master.

**Comment by jtopjian** [comment]
Looks good - thank you! :smile:

**Pull request merged**
