### PR TITLE
Acc Tests: Remove flatmap

### PR DESCRIPTION
**Pull request by jtopjian**
For #767 

This commit removes the flatmap package from tests since it has been
deprecated.

I have a feeling that this is not a permanent solution. In the future, we will still need to modify the tests to account for a new way of parsing the state. But at least we have removed flatmap, which is a good first step.

It's also unfortunate that I had to disable some VPN checks, but I have no way of testing them.

I've also moved `testAccCheckNetworkingV2Tags` out of `utils.go` and into a test file since I think that's the better location.

Finally, I renamed some VPN files to follow proper naming conventions. I understand that's not part of this fix, but figured it was small enough to do here.

### CODE REVIEW

**Comment by huangtianhua** [comment]
recheck stable/mitaka

**Comment by huangtianhua** [comment]
recheck stable/stein

**Comment by bzhaoopenstack** [comment]
recheck

**Comment by bzhaoopenstack** [comment]
recheck stable/mitaka

**Comment by bzhaoopenstack** [comment]
recheck stable/stein

**Pull request merged**
