### PR TITLE
 Internal: Use ErrDefault409 

### PR DESCRIPTION
**Pull request by jtopjian**
This commit changes all 409 checks to use the new dedicated
gophercloud.ErrDefault409 type.

### CODE REVIEW

**Comment by kiwik** [comment]
recheck

**Comment by kayrus** [comment]
recheck

**Comment by kiwik** [comment]
recheck

**Comment by jtopjian** [comment]
I'm going to go ahead and merge this since it's just replacing one type with another. It also fixes some of the test failures happening.

**Pull request merged**
