### PR TITLE
Added support for shelved compute instance to become active

### PR DESCRIPTION
**Pull request by qhua948**
Pending upstream gophercloud release for support for shelving

### CODE REVIEW

**Comment by qhua948** [comment]
#941

**Comment by qhua948** [comment]
Not sure if all the dependencies should be updated here...

**Comment by ozerovandrei** [comment]
> Not sure if all the dependencies should be updated here...

That's alright. I see that Gophercloud updated them: https://github.com/gophercloud/gophercloud/commit/ee13cae93769b396348930be7557a2a2ba7f902f

**Comment by qhua948** [comment]
Looks like openlab is finally running this time

**Comment by ozerovandrei** [comment]
Openlab is working now but new tests are failing:
```
2019-12-16 04:17:23.801082 | ubuntu-bionic | --- FAIL: TestAccComputerV2Instance_initialStateShelved (24.50s)
2019-12-16 04:17:23.801503 | ubuntu-bionic |     testing.go:569: Step 0 error: Check failed: Check 2/3 error: openstack_compute_instance_v2.instance_1: Attribute 'power_state' expected "shelved", got "active"
```
```
2019-12-16 04:17:48.141683 | ubuntu-bionic | --- FAIL: TestAccComputerV2Instance_initialStateShelvedOffloaded (24.34s)
2019-12-16 04:17:48.142114 | ubuntu-bionic |     testing.go:569: Step 0 error: Check failed: Check 2/3 error: openstack_compute_instance_v2.instance_1: Attribute 'power_state' expected "shelved_offloaded", got "active"
```

**Pull request merged**
