### PR TITLE
Support for clouds.yaml

### PR DESCRIPTION
**Pull request by jtopjian**
For #122 

@mcanevet Thank you for your patience with this. Please let me know what you think and if you see room for improvement.

### CODE REVIEW

**Comment by mcanevet** [comment]
@jtopjian Thanks a lot for this work.
I get "You must provide exactly one of DomainID or DomainName to authenticate by Username" with a clouds.yaml file containing:
```yaml
clouds:
  test:
    auth:
      auth_url: https://cloud.example.com/v3
      username: foo
      password: bar
      project_id: deadbeef
      project_name: test
      user_domain_name: example
    region_name: regionOne
    interface: public
    identity_api_version: 3
```
Any idea?

**Comment by mcanevet** [comment]
It works if I add `domain_name` in the clouds.yaml file, but somehow I don't have this key set when I download the `clouds.yaml` file for horizon...
Are you sure it shouldn't be `user_domain_name` and `user_domain_id` instead of `domain_name` and `domain_id` here: https://github.com/gophercloud/utils/blob/master/openstack/clientconfig/results.go#L28-L29 ?

**Comment by mcanevet** [comment]
@jtopjian I think it should be like that : https://github.com/gophercloud/utils/pull/3

**Comment by jtopjian** [comment]
@mcanevet Thank you for verifying this and for fixing up `gophercloud/utils`. I've rebased the vendor commit with your addition. When you have time, let me know how it's working now :)

**Comment by mcanevet** [comment]
@jtopjian works fine for me now.
Thanks a lot for this great work.

**Comment by jtopjian** [comment]
@mcanevet Perfect - thank you for testing!

@fatmcgav @catsby ping for review on this.

**Comment by jtopjian** [comment]
@catsby Thank you!

@mcanevet Thank you very much for your patience with this feature. As well, thank you again for testing it.

**Comment by mcanevet** [comment]
@jtopjian thanks a lot for implementing this.
Time for a new release?

**Pull request merged**
