### PR TITLE
Add OS_LB_ENVIRONMENT and OS_FW_ENVIRONMENT for Acc test

### LINKED ISSUE #227: Add options to control LB and FW acc test run or not
Currently we use OS_DB_ENVIRONMENT, OS_DNS_ENVIRONMENT and OS_SWIFT_ENVIRONMENT options to decide if run trove, designate and swift acc tests, but Load Balance (LB) and Firewall (FW) acc tests can't be control by using the way. In most case these services (LB and FW) are not included in regular OpenStack deployment, so if we have OS_LB_ENVIRONMENT and OS_FW_ENVIRONMENT options to decide related acc tests can be executed, it should be good.

### Terraform Version
```bash
stack@ubuntu1604 ~/tf_workspace/local $ terraform -v
Terraform v0.11.1
+ provider.openstack (unversioned)
```

### Affected Resource(s)
N/A

### Terraform Configuration Files
N/A

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
Only when users set OS_LB_ENVIRONMENT=1 and OS_FW_ENVIRONMENT=1, the related LB and FW acc tests are executed.

### Actual Behavior
LB and FW acc tests are executed by default.

### Steps to Reproduce
1. `make testacc`

### Important Factoids
N/A

### References
N/A

### PR DESCRIPTION
**Pull request by kiwik**
Add OS_LB_ENVIRONMENT and OS_FW_ENVIRONMENT options to decide related
load balance and firewall acc tests are executed or not.

Fixes #227

### CODE REVIEW

**Comment by jtopjian** [comment]
@kiwik This looks good to me. Let me know when you're ready for it to be merged or if you'd like time to test.

**Comment by kiwik** [comment]
UT and Acc tests have passed in OpenLab, this patch is ready to go, thank you, @jtopjian

**Comment by jtopjian** [comment]
@kiwik Are there separate test calls for LBaaS and FWaaS similar to the "recheck trove"? If they aren't available yet, LBaaS is a popular feature, so we should have at least that one ready to go before merging.

**Comment by kiwik** [comment]
@jtopjian you are right, they will be similar with "recheck trove", the separate tests for LBaaS and FWaaS are not yet ready in OpenLab, but in our plan. We will start to implement these after OpenLab end of the month upgrading.

**Comment by kiwik** [comment]
recheck

**Comment by kiwik** [comment]
Hi @jtopjian , FWaaS and LBaaS support have been added into OpenLab. we can use "recheck lbaas" or "recheck fwaas" to trigger those jobs when we merge this patch.

**Comment by kiwik** [comment]
We use FWaaS v1 and LBaaS v2 + Octavia deployment in terraform-provider-openstack job define.
https://github.com/theopenlab/openlab-zuul-jobs/blob/master/roles/create-devstack-local-conf/tasks/main.yml#L107
https://github.com/theopenlab/openlab-zuul-jobs/blob/master/roles/create-devstack-local-conf/tasks/main.yml#L122

**Comment by kiwik** [comment]
recheck

**Comment by jtopjian** [comment]
@kiwik Perfect! Thank you very much :)

**Pull request merged**
