### PR TITLE
Resolve LBaaS monitor crashing Terraform

### LINKED ISSUE #98: crash trying to create an openstack_lb_monitor_v2
_This issue was originally opened by @robert-cam as hashicorp/terraform#16016. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

I have an openstack lbaas v2 set up and working via terraform but terraform crashes as soon as I try to add a monitor.

### Terraform Version
crash happened on v0.10.0, updated to v0.10.3 and it's still happening.

### Terraform Configuration Files
```hcl
provider openstack {
  user_name = "user"
  tenant_name = "tenant"
}

resource "openstack_networking_network_v2" "sitebuilder-staging-net" {
  name = "sitebuilder-staging-net"
  admin_state_up = "true"
}

resource "openstack_networking_network_v2" "sitebuilder-staging-lb" {
  name = "sitebuilder-staging-lb"
  admin_state_up = "true"
}

resource "openstack_networking_subnet_v2" "sitebuilder-staging-subnet" {
  name = "sitebuilder-staging-subnet"
  network_id = "${openstack_networking_network_v2.sitebuilder-staging-net.id}"
  cidr = "10.1.1.0/24"
  region = "lon1"
  dns_nameservers = ["x","y"]
  enable_dhcp = true
  allocation_pools =
    {
      start = "10.1.1.100"
      end   = "10.1.1.200"
    }
}

resource "openstack_networking_subnet_v2" "sitebuilder-staging-lb-subnet" {
  name = "sitebuilder-staging-lb-subnet"
  network_id = "${openstack_networking_network_v2.sitebuilder-staging-lb.id}"
  cidr = "10.100.2.0/24"
  region = "lon1"
  dns_nameservers = ["x","y"]
  enable_dhcp = true
  allocation_pools =
    {
      start = "10.100.2.100"
      end   = "10.100.2.200"
    }
}

resource "openstack_networking_router_v2" "sitebuilder-staging-router" {
  name = "sitebuilder-staging-router"
  external_gateway = "aec08ef5-f630-412f-b41c-f8b81df35eea"
}

resource "openstack_networking_router_interface_v2" "staging-gw" {
  router_id = "${openstack_networking_router_v2.sitebuilder-staging-router.id}"
  subnet_id = "${openstack_networking_subnet_v2.sitebuilder-staging-subnet.id}"
}

resource "openstack_networking_router_interface_v2" "lb-gw" {
  router_id = "${openstack_networking_router_v2.sitebuilder-staging-router.id}"
  subnet_id = "${openstack_networking_subnet_v2.sitebuilder-staging-lb-subnet.id}"
}

resource "openstack_compute_floatingip_v2" "sitebuilder-staging-mgmt-floating-ip" {
  pool = "ext-net"
  region = "lon1"
}
resource "openstack_networking_floatingip_v2" "sitebuilder-staging-www-floating-ip" {
  pool = "ext-net"
  region = "lon1"
  port_id = "${openstack_lb_loadbalancer_v2.sitebuilder-staging-lb_1.vip_port_id}"
}

resource "openstack_compute_floatingip_associate_v2" "sitebuilder-staging-mgmt-floating-ip" {
  floating_ip = "${openstack_compute_floatingip_v2.sitebuilder-staging-mgmt-floating-ip.address}"
  instance_id = "${openstack_compute_instance_v2.sitebuilder-staging-mgmt.id}"
}

resource "openstack_lb_loadbalancer_v2" "sitebuilder-staging-lb_1" {
  name = "sitebuilder-staging-lb_1"
  vip_subnet_id = "${openstack_networking_subnet_v2.sitebuilder-staging-lb-subnet.id}"
}

resource "openstack_lb_listener_v2" "sb-staging-www" {
  protocol        = "HTTP"
  protocol_port   = 80
  loadbalancer_id = "${openstack_lb_loadbalancer_v2.sitebuilder-staging-lb_1.id}"
}

resource "openstack_lb_pool_v2" "pool_1" {
  name = "pool_1"
  protocol    = "HTTP"
  lb_method   = "SOURCE_IP"
  listener_id = "${openstack_lb_listener_v2.sb-staging-www.id}"
}

resource "openstack_compute_instance_v2" "sitebuilder-staging-www" {
  count = 1
  name = "sitebuilder-staging-www"
  region = "lon1"
  image_id = "5be160c1-1c60-4e96-9388-b5486c1b7c21"
  flavor_name = "g1.medium"
  network {
    name = "sitebuilder-staging-lb"
  }
}

resource "openstack_lb_member_v2" "sitebuilder-staging-www" {
  pool_id = "${openstack_lb_pool_v2.pool_1.id}"
  subnet_id = "${openstack_networking_subnet_v2.sitebuilder-staging-lb-subnet.id}"
  address = "${openstack_compute_instance_v2.sitebuilder-staging-www.network.0.fixed_ip_v4}"
  protocol_port = 80
}
resource "openstack_lb_monitor_v2" "monitor_1" {
 pool_id = "${openstack_lb_pool_v2.pool_1.id}"
  type = "HTTP"
  delay = 60
  timeout = 5
  max_retries = 3
}
resource "openstack_compute_instance_v2" "sitebuilder-staging-mgmt" {
  count = 1
  name = "sitebuilder-staging-mgmt"
  region = "lon1"
  image_id = "5be160c1-1c60-4e96-9388-b5486c1b7c21"
  flavor_name = "g1.medium"
  security_groups = ["sitebuilder-staging-www"]
  key_pair = "rc-desktop-key"
  network {
    name = "sitebuilder-staging-net"
    access_network = true
  }
  network {
    name = "sitebuilder-staging-lb"
  }
}
```

### Debug Output

https://gist.github.com/robert-cam/8c243ee81ce305255b20db5badca198e

### Crash Output
https://gist.github.com/robert-cam/895044e969783d549b80272f2b68fbd5

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
Create an openstack v2 loadbalancer with one VIP, one pool and one pool member. 
Add a monitor.
Try to create the monitor with 'terraform apply'

### PR DESCRIPTION
**Pull request by taharah**

### CODE REVIEW

**Comment by fatmcgav** [comment]
@taharah Cheers for this, all looks sensible to me.

I'll let @jtopjian have the final say though, as he's more familiar with Gophercloud then I am...

**Comment by jtopjian** [comment]
This should only update the specific gophercloud lbaas files and not all of Gophercloud. Updating all of Gophercloud  creates a very good chance of introducing numerous other bugs.

So this PR should really only have 1-2 files updated.

I have plans to look into a full vendor update and make sure all acceptance tests pass sometime in the near future.

**Comment by jtopjian** [comment]
Additionally, AFAIK, there have been no recent changes to Gophercloud's LBaaS support, except for godoc updates. I might be wrong about that. I recommend double-checking the diff's of the actual lbaas files.

If it's only godoc, then really the only commit needed is https://github.com/terraform-providers/terraform-provider-openstack/pull/102/commits/b5edf23fcdd4474ef5aaa2a823a6488935d47aa5

**Comment by taharah** [comment]
@jtopjian you are correct and that the only changes specific to LBaaS was Godoc updates. I've gone ahead and dropped the two changes that updated all of gophercloud.

**Comment by jtopjian** [comment]
@taharah Thank you for looking into that :)

I'll review this later this evening.

**Comment by jtopjian** [comment]
@taharah This looks good to me. Thank you for submitting this!

**Pull request merged**
