### PR TITLE
Keymanager V1: fix ACL set for the "certificate" container type

### LINKED ISSUE #1005: openstack_keymanager_container_v1 creation failed with http 400 error
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see https://www.terraform.io/community.html.

### Terraform Version
```
terraform -v
Terraform v0.12.24
+ provider.openstack v1.27.0
+ provider.tls v2.1.1
```

### Affected Resource(s)
- openstack_keymanager_container_v1

### Terraform Configuration Files
```hcl
resource "tls_private_key" "continuous_test_lb_private_key" {
  algorithm   = "RSA"
  rsa_bits    = "4096"
}

resource "tls_self_signed_cert" "continuous_test_lb_cert" {
  key_algorithm   = tls_private_key.continuous_test_lb_private_key.algorithm
  private_key_pem = tls_private_key.continuous_test_lb_private_key.private_key_pem

  subject {
    common_name  = "nginx.continuous-test.cloud-lab.620nm.net"
    organization = "OBS"
  }

  validity_period_hours = 1

  allowed_uses = [
    "key_encipherment",
    "digital_signature",
    "server_auth",
  ]
}

resource "openstack_keymanager_secret_v1" "continuous_test_lb_private_key_secret" {
  name                 = "continuous_test_lb_private_key"
  payload              = tls_private_key.continuous_test_lb_private_key.private_key_pem
  payload_content_type = "text/plain"
  secret_type          = "private"
}

resource "openstack_keymanager_secret_v1" "continuous_test_lb_cert_secret" {
  name                 = "continuous_test_lb_cert"
  payload              = tls_self_signed_cert.continuous_test_lb_cert.cert_pem
  payload_content_type = "text/plain"
  secret_type          = "certificate"
}

resource "openstack_keymanager_container_v1" "continuous_test_lb_tls_secret" {
  name = "continuous_test_lb_tls"
  type = "certificate"

  secret_refs {
    name       = "certificate"
    secret_ref = openstack_keymanager_secret_v1.continuous_test_lb_cert_secret.secret_ref
  }

  secret_refs {
    name       = "private_key"
    secret_ref = openstack_keymanager_secret_v1.continuous_test_lb_private_key_secret.secret_ref
  }
}
```

### Debug Output
https://gist.github.com/lperrin-obs/3b109c7d4b4c87308abb4a47f691010b

### Expected Behavior
Container should be created correctly

### Actual Behavior
The container is created but with no secret inside

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Openstack version is Queens

### PR DESCRIPTION
**Pull request by kayrus**
Resolves #1005

### CODE REVIEW

**Comment by dylanmtaylor** [comment]
The only failures I am seeing are related to volume attachments which would not be part of this change. 

https://logs.openlabtesting.org/logs/46/1046/7217927363b9cb7e3ebb881f530c496a35efac2f/check/terraform-provider-openstack-acceptance-test/83e32fc/test_results.html

**Comment by kayrus** [comment]
@ozerovandrei ready for review

**Comment by dylanmtaylor** [comment]
I just compiled this from source and tested out an apply, it looks like it fixes the issue with creating the container.

**Comment by kayrus** [comment]
@dylanmtaylor 

> I just compiled this from source and tested out an apply, it looks like it fixes the issue with creating the container.

Yes, I added corresponding functional tests and they also pass in CI pipeline.

**Review by ozerovandrei — APPROVED** [review]
LGTM

**Pull request merged**
