### PR TITLE
LBaaSv2: Prioritize loadbalancer's status in favour of subelements

### PR DESCRIPTION
**Pull request by kayrus**
Part of the #546

Let's see the test results

### CODE REVIEW

**Comment by kayrus** [comment]
recheck lbaas

**Comment by jtopjian** [comment]
Just a heads up that I probably won't get a chance to look at this for a few days.

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
Rebased on #522

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
@jtopjian ready for review

**Comment by jtopjian** [comment]
ack - I'll look at this very shorty.

**Comment by jtopjian** [comment]
@kayrus Instead of nesting the refresh functions, what about modifying each of the individual resource refresh functions like this:

```go
func resourceLBV2ListenerRefreshFunc(lbClient *gophercloud.ServiceClient, lbID, listenerID string) resource.StateRefreshFunc {
  return func() (interface{}, string, error) {
    lb, err := loadbalancers.Get(lbClient, lbID).Extract()
    if err != nil {
      return nil, "", err
    }

    if !strSliceContains(lbSkipLBStatuses, lb.ProvisioningStatus) {
      return lb, lb.ProvisioningStatus, nil
    }

    listener, err := listeners.Get(lbClient, listenerID).Extract()
    if err != nil {
      return nil, "", err
    }

    return listener, listener.ProvisioningStatus, nil
  }
}
```

The loadbalancer check is repeated, but it makes the code more readable.

**Comment by kayrus** [comment]
recheck lbaas

**Pull request merged**
