### PR TITLE
feat: add floating_ip_enabled in containerinfra

### PR DESCRIPTION
**Pull request by galuszkak**

### CODE REVIEW

**Comment by galuszkak** [comment]
I've looked on failing tests, but it doesn't seem like this is a fault from my code change as it isn't related to those tests at all. 

cc // @ozerovandrei @jtopjian

**Comment by kayrus** [comment]
Tests fail because volume attachments doesn't contain a hostname anymore. See more details https://github.com/theopenlab/openlab/issues/571

**Comment by galuszkak** [comment]
What I have to do to get this reviewed & merged?

Thanks!

**Review by ozerovandrei — APPROVED** [review]
LGTM

**Pull request merged**
