### PR TITLE
add server tags

### PR DESCRIPTION
**Pull request by npu21**
server tags is a frequently used feature, so I add server tags support for nova servers

### CODE REVIEW

**Comment by kiwik** [comment]
recheck

**Comment by kiwik** [comment]
recheck

**Comment by kiwik** [comment]
recheck

**Comment by jtopjian** [comment]
@npu21 This feature still needs to be merged upstream: https://github.com/gophercloud/gophercloud/pull/1115

It looks like you have modified the vendor files locally (Travis is reporting this error):

```
$ make vendor-status
The following packages are missing or modified locally:
	github.com/gophercloud/gophercloud/openstack/compute/v2/servers
Error: status failed for 1 package(s)
make: *** [vendor-status] Error 2
The command "make vendor-status" exited with 2.
```

Vendor files shouldn't be modified locally since that will cause them to deviate from upstream, so we'll have to wait until the upstream PR is merged.

I propose closing this PR for now. A new PR can be created once the PR has been merged upstream.

**Comment by npu21** [comment]
@jtopjian @kiwik ,ok, will reopen it once the gophercloud PR merged.
Thanks!

**Comment by eandersson** [comment]
Can we re-open this?

**Comment by jtopjian** [comment]
@eandersson The implementation would be quite different than what's in this PR. Instead, I've created an issue to track this request: https://github.com/terraform-providers/terraform-provider-openstack/issues/722

**Comment by eandersson** [comment]
> @eandersson The implementation would be quite different than what's in this PR. Instead, I've created an issue to track this request: #722

Perfect - thanks!

**Pull request closed without merging**
