### PR TITLE
Swift: run tempurl acceptance tests with slashes in object name

### PR DESCRIPTION
**Pull request by kayrus**
Ref: https://github.com/gophercloud/gophercloud/issues/1993

### CODE REVIEW

**Comment by kayrus** [comment]
recheck

**Comment by kayrus** [comment]
recheck

**Comment by Lirt** [comment]
That's extremely hard to read those logs, but I think this is what we look for:

```bash
Class:github.com/terraform-providers/terraform-provider-openstack/openstack
Test Name:TestAccOpenStackObjectStorageTempurlV1_basic
Running Time:0.79
State:Failed

2020/07/25 20:19:18 [DEBUG] Starting graph walk: walkPlanDestroy testing.go:684: Step 0 error: Check failed: Check 2/5 error: Tempurl body doesn't match the expected data: 401 Unauthorized: Temp URL invalid
```

**Comment by kayrus** [comment]
@Lirt that's what I wanted to get. I'll wait once your patch is merged and bumb gophercloud dependency to resolve an issue.

**Comment by kayrus** [comment]
recheck

**Comment by kayrus** [comment]
recheck

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck

**Comment by kayrus** [comment]
recheck

**Comment by kayrus** [comment]
recheck

**Comment by bzhaoopenstack** [comment]
recheck

**Comment by kayrus** [comment]
recheck

**Comment by kayrus** [comment]
recheck

**Comment by kayrus** [comment]
recheck

**Comment by kayrus** [comment]
recheck

**Comment by kayrus** [comment]
@ozerovandrei ready for review. Failed tests relate to volume attach

**Review by ozerovandrei — APPROVED** [review]
LGTM

**Pull request merged**
