### PR TITLE
Keymanager V1: secrets resource

### LINKED ISSUE #352: Support barbican resources
It would be nice to support Barbican API in Terraform, so that SSL-terminating loadbalancers could be deployed fully via terraform.

### Terraform Version
0.11.7

### Affected Resource(s)
- openstack_lb_listener_v2

### Terraform Configuration Files
N/A

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
I can add barbican secrets via terraform.

### Actual Behavior
I can't add barbican secrets via terraform.

### Steps to Reproduce
1. Try to set up SSL-terminating loadbalancer using Terraform
2. Be disappointed

### Important Factoids
This has come up already, but in a different context

### References
- https://github.com/terraform-providers/terraform-provider-openstack/issues/76

### PR DESCRIPTION
**Pull request by kayrus**
Originally written by @simonre 
Fixes #352
Supersedes #650

### CODE REVIEW

**Comment by kayrus** [comment]
recheck

**Comment by kayrus** [comment]
I successfully ran tests locally, though @jtopjian can you ask openlab team to enable barbican env variable (`export OS_KEYMANAGER_ENVIRONMENT=true`)?

```
--- SKIP: TestAccKeyManagerSecretV1_importBasic (0.00s)
    provider_test.go:147: This environment does not support Barbican Keymanager tests
```

**Comment by kayrus** [comment]
@jtopjian @ozerovandrei @simonre ready for review

**Comment by kayrus** [comment]
recheck

**Comment by kayrus** [comment]
recheck

**Comment by ozerovandrei** [comment]
@kayrus I created the issue [openlab#324](https://github.com/theopenlab/openlab/issues/324) but I don't think that we need to wait for them since you already tested those changes manually.

What do you think?

**Comment by kayrus** [comment]
@ozerovandrei sure.

**Pull request merged**
