### PR TITLE
LBaaS v2: Add batch members update resource

### LINKED ISSUE #889: LBaaSv2: Add Octavia batch members update support
### Affected Resource(s)
Please list the resources as a list, for example:
- openstack_lb_member**s**_v2

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Expected Behavior

Octavia supports batch members update. It reduces an amount of API calls and speeds up the configuration process. I suggest to add the `openstack_lb_members_v2` resource to handle this.

### References

- https://github.com/gophercloud/gophercloud/issues/1217

### PR DESCRIPTION
**Pull request by kayrus**
Resolves #889

### CODE REVIEW

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
It's not possible to unset members. With the `"members": null` request Octavia responses:

```json
{
  "debuginfo": null,
  "faultcode": "Server",
  "faultstring": "'NoneType' object is not iterable"
}
```

with the `"members": []` Octavia responses:

```json
{
  "debuginfo": null,
  "faultcode": "Server",
  "faultstring": "Provider 'amphora' reports error: list index out of range"
}
```

However, within the `vexxhost` hosting, the `"members": []` request works fine.

I can add a workaround, which will keep only one member and then remove it individually.

/cc @jtopjian @ozerovandrei

**Comment by kayrus** [comment]
recheck lbaas

**Comment by ozerovandrei** [comment]
Same error on Selectel OpenStack cloud.

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
https://review.opendev.org/688548 has been merged

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
according to logs tests passed. Removing the debug commit.

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by ozerovandrei** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
@ozerovandrei I suggest just to merge this. Tests don't relate to this PR, it is an openlab issue.

**Pull request merged**
