### PR TITLE
Internal: fix schema set for the subnet resource

### PR DESCRIPTION
**Pull request by kayrus**
Refs to #601
For #456

### CODE REVIEW

**Comment by kayrus** [comment]
@jtopjian ready for review

**Comment by jtopjian** [comment]
@kayrus Is it possible to include an acceptance test that validates this?

**Comment by kayrus** [comment]
@jtopjian it is possible :)

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck fwaas

**Comment by kayrus** [comment]
recheck vpnaas

**Comment by kayrus** [comment]
recheck designate

**Comment by kayrus** [comment]
recheck trove

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck fwaas

**Comment by kayrus** [comment]
recheck designate

**Comment by kayrus** [comment]
recheck trove

**Comment by kayrus** [comment]
@jtopjian any update here?

**Comment by kayrus** [comment]
@jtopjian looks like I opened yet another Pandora box.

Your branch looks fine. Only one addition: does it make sense to introduce a `DiffSuppressFunc` function in your implementation as well? If I'm not mistaken, it can help to handle ordering issue:

```go
DiffSuppressFunc: func(k, old, new string, d *schema.ResourceData) bool {
        // Only work with existing instances
        if d.Id() == "" {
                return false
        }
        // Only work with missing configurations
        if new != "" {
                ... ... ...
        }
        // Only work when already set in Terraform state
        if old == "" {
                ... ... ...
        }
        return true
},
```

Can we detect the ordering inside the `DiffSuppressFunc` for TypeSets?

**Comment by jtopjian** [comment]
> Only one addition: does it make sense to introduce a DiffSuppressFunc function in your implementation as well? If I'm not mistaken, it can help to handle ordering issue:

It's possible, but I'm hesitant to do it. I looked into this for the DNS recordset solution and there was something about it that made me not want to do it - I need to revisit it. I hope to be able to get back to that shortly.

**Comment by jtopjian** [comment]
`DiffSuppressFunc` and the other functions that handle state manipulation actually write the modified state. So if a user specified an order as 1, 2, 3 and the returned order was 2, 3, 1, then `DiffSuppressFunc` _could_ say there is no diff, but it would write 2, 3, 1 to state. I wish there was an ability to not write to state.

After reviewing everything after some days, I still think the fix I've done in my branch is good to go. It's essentially the same thing as the DNS stuff, but without any bracket manipulation.

Unless there are objections, I've opened #645 and will use that as the solution.

**Comment by kayrus** [comment]
I'll take another look on the #645 within this week

**Comment by kayrus** [comment]
Closing in favor of #668

**Pull request closed without merging**
