### PR TITLE
allow resize for stopped VMs (#347)

### PR DESCRIPTION
**Pull request by bogdansavu**

### CODE REVIEW

**Comment by jtopjian** [comment]
recheck

**Comment by jtopjian** [comment]
recheck

**Comment by jtopjian** [comment]
@bogdansavu What happens if a user specifies a state of `shutoff` when the instance is initially created?

Additionally, where you have:

```
d.Set("state", strings.ToLower(server.Status))
```

What happens if `server.Status` is `ERROR`?

**Comment by bogdansavu** [comment]
@jtopjian I created a new PR for (#349).

**Pull request merged**
