### PR TITLE
Use "openstack_compute_floatingip_v2"

### PR DESCRIPTION
**Pull request by dinakar29**
Use "openstack_compute_floatingip_v2" instead of outdated "openstack_networking_floatingip_v2"

### CODE REVIEW

**Comment by jtopjian** [comment]
@dinakar29 The `openstack_networking_floatingip_v2` resource is actually the newer resource. It uses the Neutron API which is the standard networking service for OpenStack.

The `openstack_compute_instance_v2` resource is the deprecated resource since it uses the Nova API to manage floating IPs. Nova used to proxy these API requests in effect creating Neutron-based floating IPs behind the scenes. Recent versions of OpenStack have removed this entirely and so `openstack_compute_floatingip_v2` will no longer work on newer releases of OpenStack.

However, the API to _associate_ a floating IP is still controlled by the Nova API and is still valid.

Please let me know if you have any questions.

**Comment by dinakar29** [comment]
Thanks for the quick response, @jtopjian. I am using the Queens release of OpenStack which uses the Neutron API. Note that this is a Rackspace hosted instance of OpenStack.

The version of Terraform I am using is v0.11.7 and v1.3.0 of the OpenStack provider, but I still see an issue with using `openstack_networking_floatingip_v2`:
```
$ terraform version
Terraform v0.11.7
+ provider.null v1.0.0
+ provider.openstack v1.3.0

$ terraform plan
Error: resource 'openstack_compute_floatingip_associate_v2.terraform_instance' config: unknown resource 'openstack_networking_floatingip_v2.terraform_instance' referenced in variable openstack_networking_floatingip_v2.terraform_instance.address
```

Here's what I'm using setup:

```
resource "openstack_networking_floatingip_v2" "terraform_instance" {
  floating_ip = "${openstack_compute_floatingip_v2.terraform_instance.address}"
  instance_id = "${openstack_compute_instance_v2.terraform_instance.id}"
}
```

This works with `openstack_networking_floatingip_v2`. Any ideas?

**Comment by jtopjian** [comment]
> This works with openstack_networking_floatingip_v2. Any ideas?

Actually I'm a little confused. Is it working with `openstack_networking_floatingip_v2`?

The error you've provided is a Terraform error and not an OpenStack error. This means that the error is most likely within the Terraform configuration itself -- maybe a typo or something similar?

**Comment by dinakar29** [comment]
Ah sorry about the confusion. I meant "openstack_compute_floatingip_v2" is working fine.

Let me reiterate for clarity. When I try:

```
resource "openstack_compute_floatingip_v2" "terraform_instance" {
  floating_ip = "${openstack_compute_floatingip_v2.terraform_instance.address}"
  instance_id = "${openstack_compute_instance_v2.terraform_instance.id}"
}
```

It works fine.

But when I do:
```
resource "openstack_networking_floatingip_v2" "terraform_instance" {
  floating_ip = "${openstack_compute_floatingip_v2.terraform_instance.address}"
  instance_id = "${openstack_compute_instance_v2.terraform_instance.id}"
}
```

It throws that error on executing `terraform plan`. 

Do you think this is a syntactical error?

**Comment by jtopjian** [comment]
@dinakar29 Your Terraform configuration should look similar to the following:

```hcl
resource "openstack_compute_instance_v2" "instance_1" {
  name            = "instance_1"
  image_id        = "ad091b52-742f-469e-8f3c-fd81cadf0743"
  flavor_id       = 3
  key_pair        = "my_key_pair_name"
  security_groups = ["default"]
}

resource "openstack_networking_floatingip_v2" "fip_1" {
  pool = "my_pool"
}

resource "openstack_compute_floatingip_associate_v2" "fip_1" {
  floating_ip = "${openstack_networking_floatingip_v2.fip_1.address}"
  instance_id = "${openstack_compute_instance_v2.instance_1.id}"
}
```

The second resource is `openstack_networking_floatingip_v2` which creates a floating IP via the Neutron API.

The third resource is `openstack_compute_floatingip_associate_v2` with "associate" in the title. This resource is different than `openstack_compute_floatingip_v2` (without "associate" in the title), which is the older/deprecated way of allocating a floating IP.

**Comment by dinakar29** [comment]
Ah ok. Understood. Thanks a ton for your input!

**Pull request closed without merging**
