### PR TITLE
Use HasChange for openstack_fw_rule Update

### PR DESCRIPTION
**Pull request by niuzhenguo**
This changes to use HasChange to construct the update options instead
of sending the whole body even if the unchanged attributes.

### CODE REVIEW

**Comment by jtopjian** [comment]
@niuzhenguo I'm getting an error when I run the [acceptance test](https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/resource_openstack_fw_rule_v1_test.go#L15-L75) for this:

```
2018/01/11 02:42:51 [DEBUG] Updating firewall rules: rules.UpdateOpts{Protocol:(*string)(nil), Action:(*string)(nil), Name:(*string)(nil), Description:(*string)(0xc420526d90), IPVersion:(*gophercloud.          IPVersion)(nil), SourceIPAddress:(*string)(0xc420526ed0), DestinationIPAddress:(*string)(0xc420526fd0), SourcePort:(*string)(0xc420526f50), DestinationPort:(*string)(0xc420527050), Shared:(*bool)(nil), Enabled:(*bool)(nil)}
2018/01/11 02:42:51 [DEBUG] OpenStack Request URL: PUT http://199.116.235.43:9696/v2.0/fw/firewall_rules/4a83c9a5-7323-43bb-95e3-b4310883dca3
2018/01/11 02:42:51 [DEBUG] Openstack Request Headers:
Accept: application/json
Content-Type: application/json
User-Agent: Terraform 0.10.0-dev (go1.9) gophercloud/2.0.0
X-Auth-Token: ***
2018/01/11 02:42:51 [DEBUG] OpenStack Request Body: {
  "firewall_rule": {
    "description": "Terraform accept test",
    "destination_ip_address": "4.3.2.0/24",
    "destination_port": "555",
    "source_ip_address": "1.2.3.4",
    "source_port": "444"
  }
}
2018/01/11 02:42:52 [DEBUG] Openstack Response Code: 400
2018/01/11 02:42:52 [DEBUG] Openstack Response Headers:
Content-Length: 161
Content-Type: application/json
Date: Thu, 11 Jan 2018 02:42:52 GMT
X-Openstack-Request-Id: req-68bc2327-4264-492f-a18e-a7c5a02dc0e6
2018/01/11 02:42:52 [DEBUG] OpenStack Response Body: {
  "NeutronError": {
    "detail": "",
    "message": "Source, destination port are not allowed when protocol is set to ICMP.",
    "type": "FirewallRuleInvalidICMPParameter"
  }
}
```

It seems that because a protocol isn't being passed in the PUT request, the firewall service thinks the protocol is ICMP.

**Comment by niuzhenguo** [comment]
@jtopjian that sounds like a bug of Neutron?

**Comment by jtopjian** [comment]
@niuzhenguo It's quite possible (I tested this on Pike), but because of that either some fields of the PUT must be sent all of the time _or_ we have to continue sending all of the fields (I imagine this is why it was originally coded this way in this resource).

Are you running into an error when sending all fields? If so, can you let me know your test case?

By the way, thank you for submitting this PR.

**Comment by niuzhenguo** [comment]
@jtopjian yes, I'm getting an error when only updating rule name

```
"NeutronError": {
  "detail": "",
  "message": "Invalid input for source_port. Reason: Port '' is not a valid number.",
  "type": "HTTPBadRequest"
}
```

The update body uses "" for unchanged fields instead of null
```
"firewall_rule": {
    "action": "deny",
    "description": "drop TELNET traffic",
    "destination_ip_address": "",
    "destination_port": "24",
    "enabled": true,
    "ip_version": 4,
    "name": "terraform_rule-1-update-two1",
    "protocol": "tcp",
    "source_ip_address": "",
    "source_port": ""
}
```

**Comment by animationzl** [comment]
recheck

**Comment by niuzhenguo** [comment]
recheck stable/pike

**Comment by jtopjian** [comment]
Since the branch to this PR seems to have disappeared, I'm going to close this PR in favor of #224.

**Pull request closed without merging**
