### PR TITLE
Networking v2: Fix Allowed Address Pairs validation

### PR DESCRIPTION
**Pull request by kayrus**
An alternative fix for #661

### CODE REVIEW

**Comment by kayrus** [comment]
@ozerovandrei @jtopjian , kindly review this PR.

**Comment by jtopjian** [comment]
@kayrus This looks like a legitimate fix, but I would prefer to just revert back to the original configuration for now. I'm behind on the code cleanup and preparing for v0.12 and I don't want to minimize possibilities of further bugs right now.

**Comment by kayrus** [comment]
If you don't mind, I'll keep it open for the future.

**Comment by jtopjian** [comment]
Absolutely :)

**Pull request closed without merging**
