### PR TITLE
vendor: update gophercloud/*

### PR DESCRIPTION
**Pull request by stbenjam**
This PR updates gophercloud/gophercloud and gophercloud/utils, and fixes a couple of option struct members that changed to pointers

### CODE REVIEW

**Comment by stbenjam** [comment]
@jtopjian I hope this change is OK... the reasons behind it aren't really related to this project so I could understand why you might not want this change.

I need this provider to co-exist with https://github.com/openshift-metal3/terraform-provider-ironic in openshift's installer.  That requires a newer gophercloud, which breaks this provider.

**Comment by jtopjian** [comment]
>  I hope this change is OK... the reasons behind it aren't really related to this project so I could understand why you might not want this change.

Totally fine - thank you!

**Comment by stbenjam** [comment]
Thanks so much! Do you know when you might release 1.18?

**Comment by jtopjian** [comment]
"soon" :)

Once we get a fix for #742, that will warrant a release. Hopefully within the next week.

**Pull request merged**
