### PR TITLE
Check type assertion for the dns_nameservers in subnet

### LINKED ISSUE #723: Networking V2: setting an empty dns_nameservers for the subnet resource causes panic
### Affected Resource(s)
Please list the resources as a list, for example:
- openstack_networking_subnet_v2

### Terraform config

```hcl
resource "openstack_networking_subnet_v2" "subnet_1" {
  network_id = "${openstack_networking_network_v2.network_1.id}"
  cidr       = "192.168.199.0/24"
  dns_nameservers = []
}
```

### Panic Output
https://gist.github.com/kayrus/2fa7e6756298951a21344f389f6d3cbc

### PR DESCRIPTION
**Pull request by kayrus**
Resolves #723

### CODE REVIEW

**Comment by kayrus** [comment]
@jtopjian you might want to take a look on the `TestAccComputeV2Instance_blockDeviceNewVolumeTypeAndBus` error. it is not related to this PR.

**Comment by jtopjian** [comment]
@kayrus Thanks for the heads up.

Given the other test suite passed, this might have been a transient error or something specific to the OpenLab node the test was run on. If it keeps happening, I'll open a ticket with OpenLab.

**Comment by kayrus** [comment]
recheck

**Comment by kayrus** [comment]
@jtopjian ready for review

**Comment by jtopjian** [comment]
@kayrus This looks good to me - thank you! I'll let @ozerovandrei do the approve and merge.

Just a heads up: I've stepped down from this project in the past few weeks. Unfortunately I don't have enough time these days to work on this project in the detail it deserves. I'm still working on Gophercloud, though.

**Pull request merged**
