### PR TITLE
Add description field to openstack_networking_secgroup_rule_v2

### PR DESCRIPTION
**Pull request by jsm222**
For #419

### CODE REVIEW

**Comment by jsm222** [comment]
gophercloud/gophercloud#1230

**Comment by ozerovandrei** [comment]
@jsm222 Hello.

I will add a [WIP] to a title since those changes can't be added as-is because they're depend on upstream library implementation.

We need to add [#1231](https://github.com/gophercloud/gophercloud/pull/1231) into Gophercloud first.
And then the latest Gophercloud code must be added into `vendor` via the `govendor` tool. It can't be just edited inside vendor directory.

Also it will be better if you create an issue for this PR.

You can read more about development process there: [testing-and-development](https://www.terraform.io/docs/providers/openstack/index.html#testing-and-development)

**Comment by jsm222** [comment]
[#1231](gophercloud/gophercloud#1231) is merged. How do I update the gophercloud vendor correctly with govendor? I'm quite new to  golang.. Thanks

**Comment by jsm222** [comment]
Gave it a shot and missed. 

> govendor sync; 
> make test

works locally..

**Comment by jtopjian** [comment]
@jsm222 No problem at all - we need to update the developer documentation on how to use `govendor`.

Try this command:

```
govendor fetch github.com/gophercloud/gophercloud/...@a5e4374c99156e0f98429d363ace306d8f9fff6d
```

What this will do is bring all of Gophercloud up-to-date with the latest commit. You'll see that there are other files in `vendor` which are updated and that's OK. It's usually best to have the vendor update in a separate commit from the actual Terraform changes.

Let me know if this helps or if you run into any problems.

**Comment by jtopjian** [comment]
@jsm222 Perfect :smile: 

The last part is to update the documentation with the new field: https://github.com/terraform-providers/terraform-provider-openstack/blob/master/website/docs/r/networking_secgroup_rule_v2.html.markdown

**Comment by ozerovandrei** [comment]
@jsm222 thank you for adding this feature!

**Pull request merged**
