### PR TITLE
Add compute_instance_v2 data source

### LINKED ISSUE #982: Feature request: create `data_source_openstack_compute_instance_v2`
Hi there,

### Terraform Version

0.12.24

### Affected Resource(s)

n/a, requesting a new feature

### Terraform Configuration Files
```hcl
data "openstack_compute_instance_v2" "instance" {
  name = "instance_name"
}
```

### Expected Behavior

n/a, feature request

### Actual Behavior
n/a, feature request

### References

The existing `resource_openstack_compute_instance_v2.go` would contain everything this needs, I think? I don't know enough golang to know if this is true, though.

### PR DESCRIPTION
**Pull request by aurynn**
Resolves #982 

This is largely copied from `resource.openstack_compute_instance_v2`.

I've checked the data source itself locally, but I have no way to run the full test suite, so relying on project CI.

### CODE REVIEW

**Comment by kayrus** [comment]
Resolves #717 as well

**Comment by aurynn** [comment]
Was able to validate and fix the test locally.

**Comment by aurynn** [comment]
@ozerovandrei Yep, I think this is ready to be merged in. 

I definitely understand the desire to not add too much that'll have to be migrated over when you start implementing the new `openstack_compute_server_v2` API. Do you have any ideas when/if/etc you'll have the capacity to start picking up that work/maintaining this provider more?

**Comment by ozerovandrei** [comment]
> Do you have any ideas when/if/etc you'll have the capacity to start picking up that work/maintaining this provider more?

Unfortunately I don't 😞

**Pull request merged**
