### PR TITLE
add option to use octavia service for lb operations

### PR DESCRIPTION
**Pull request by jrperritt**
for #147

### CODE REVIEW

**Comment by jrperritt** [comment]
OK, this one's ready for a first look.

**Comment by jrperritt** [comment]
I went with one `use_octavia` config field in the provider. Originally I had a field in each LB V2 resource schema but, as was pointed out to me, having even one of those not set to true while another is would fail to deploy correctly.

**Comment by jtopjian** [comment]
> having even one of those not set to true while another is would fail to deploy correctly.

Good call. Provider-level is definitely the way to go.

I like `use_octavia` because it's a decisive boolean, but so this discussion can be done now instead of later (and also so the discussion is documented): is there benefit to instead having `loadbalancer_service` with options of `neutron` and `octavia`, defaulting to `neutron`?

`loadbalancer_service` accounts for a future possibility of yet another load balancing service. That might never happen. I can also see a user accidentally setting it to the actual load balancing driver like "f5".

All in all, this change looks good to me. I'll need to run some compiled tests before and after this patch to note changes (if any) to an existing state file. Just a heads up that this might take me a day or two to get to.

**Comment by jrperritt** [comment]
> is there benefit to instead having loadbalancer_service with options of neutron and octavia, defaulting to neutron?

Great question. This `use_octavia` option is only necessary until they deprecate (or, maybe, remove) LB operations in Neutron, at which point it would be deprecated here, so that's unfortunate. 

When creating an LB in Neutron, there is a `loadbalancer_provider` option. If you set that to "octavia", then Neutron will proxy LB requests to Octavia. From what I've been told (and what we've experienced at $WORK), the Neutron and Octavia databases can get out of sync, and the only way to fix it is to make manual changes to the database.

**Comment by jrperritt** [comment]
Another option I hadn't considered for this is to not have a config field and instead just look for an environment variable. So instead of having `use_octavia` with a default of `$OS_USE_OCTAVIA`, it would just look for `$OS_USE_OCTAVIA` when the config is created. That would prevent creating the specific and temporary config field. Not sure if that would be better.

**Comment by jtopjian** [comment]
I think the way it's configured now is fine.

I'm not concerned about the field being temporary. In fact, I think it'll stick around for quite a while. When Octavia becomes the official load balancer service, there will still be a lot of Neutron-based lb services around. Once Octavia has become the majority deployed, `use_octavia` can be set to a default value of `true`.

If/when the time comes to remove it, Terraform has an excellent process of deprecating fields: the field gets tagged as `deprecated` but still works, then it gets tagged as `removed` which allows an error, but doesn't break schemas.

**Comment by jrperritt** [comment]
> I get an error when setting this to true, which is expected since I don't have the Octavia service, so it's definitely working.

Yeah, I couldn't think of a good way to test this (as in, a good test to write). From the user's perspective, everything should look the same whether using Neutron or Octavia.

**Comment by jtopjian** [comment]
LGTM - thank you for adding this.

**Comment by jrperritt** [comment]
@jtopjian Thank you for reviewing and testing this.

I also wanted to ask inre releases: I took a look at the existing releases, and it looks like maybe they are created as-needed/as-asked-for? Asking because we'd be interested in seeing a release that has this PR as well as the DNS V2 zone data source.

**Comment by jtopjian** [comment]
Indeed - releases are done ad hoc at the moment.

I'll look at getting a release out this week. There seems to be some flaky AWS issues which are causing the nightly CI to fail. Once I can get it to go green, we should be good.

**Comment by jrperritt** [comment]
Great, thanks :)

**Pull request merged**
