### PR TITLE
FWaaS v1: fixing rule acceptance tests

### LINKED ISSUE #342: Unexpect ProjectID attribute cause FWaaS Acc tests failed
ACC tests failing in OpenLab testing, that cause by unexpect `ProjectID` attribute.
- TestAccFWRuleV1_basic
- TestAccFWRuleV1_anyProtocol
- TestAccFWRuleV1_updateName

```bash
Expected: 
&rules.Rule{ID:"b313ed8a-2019-4cf6-9992-06b7905c7cdb", Name:"rule_1", Description:"", Protocol:"udp", Action:"deny", IPVersion:4, SourceIPAddress:"", DestinationIPAddress:"", SourcePort:"", DestinationPort:"", Shared:false, Enabled:true, PolicyID:"", Position:0, TenantID:"", ProjectID:""} 
Found: 
&rules.Rule{ID:"b313ed8a-2019-4cf6-9992-06b7905c7cdb", Name:"rule_1", Description:"", Protocol:"udp", Action:"deny", IPVersion:4, SourceIPAddress:"", DestinationIPAddress:"", SourcePort:"", DestinationPort:"", Shared:false, Enabled:true, PolicyID:"", Position:0, TenantID:"", ProjectID:"c8e96ca4f3dd4c789b13955f73adc9a7"}
```
Log file defailt: http://logs.openlabtesting.org/logs/35/335/c51eb79051a39911dc05ea1891e29a01e1d48b5e/recheck-fwaas/terraform-provider-openstack-acceptance-test-fwaas/5d4692e/job-output.txt.gz

NOTE: there are other test failings in log, this issue trace test cases, include: 
- TestAccFWRuleV1_basic
- TestAccFWRuleV1_anyProtocol
- TestAccFWRuleV1_updateName

### Terraform Version
N/A

### Affected Resource(s)
- openstack_fw_rule_v1

### Terraform Configuration Files
N/A

### Debug Output
```bash
Expected: 
&rules.Rule{ID:"b313ed8a-2019-4cf6-9992-06b7905c7cdb", Name:"rule_1", Description:"", Protocol:"udp", Action:"deny", IPVersion:4, SourceIPAddress:"", DestinationIPAddress:"", SourcePort:"", DestinationPort:"", Shared:false, Enabled:true, PolicyID:"", Position:0, TenantID:"", ProjectID:""} 
Found: 
&rules.Rule{ID:"b313ed8a-2019-4cf6-9992-06b7905c7cdb", Name:"rule_1", Description:"", Protocol:"udp", Action:"deny", IPVersion:4, SourceIPAddress:"", DestinationIPAddress:"", SourcePort:"", DestinationPort:"", Shared:false, Enabled:true, PolicyID:"", Position:0, TenantID:"", ProjectID:"c8e96ca4f3dd4c789b13955f73adc9a7"}
```
### Panic Output
N/A

### Expected Behavior
ACC tests pass
- TestAccFWRuleV1_basic
- TestAccFWRuleV1_anyProtocol
- TestAccFWRuleV1_updateName

### Actual Behavior
ACC tests failed

### Steps to Reproduce
Run FWaaS accpetance tests

### Important Factoids
N/A

### References
N/A

### PR DESCRIPTION
**Pull request by jtopjian**
Fixes #342

### CODE REVIEW

**Comment by jtopjian** [comment]
recheck fwaas

**Comment by jtopjian** [comment]
recheck fwaas

**Comment by kiwik** [comment]
recheck

**Comment by kiwik** [comment]
Hi @jtopjian , Seems fwaas instance can not be created in devstack, we are trying to find out root reason, sorry for the delay.

**Comment by jtopjian** [comment]
@kiwik Sounds good! Thank you for looking into this and no rush on the fix. I've confirmed that everything is working locally, so this is really just a matter of test errors and not actual errors :)

**Comment by kiwik** [comment]
recheck fwaas

**Comment by kiwik** [comment]
recheck fwaas

**Comment by kiwik** [comment]
recheck

**Comment by kiwik** [comment]
recheck

**Comment by kiwik** [comment]
recheck fwaas

**Comment by kiwik** [comment]
Hi @jtopjian , I have updated OpenLab side config, now only following two tests failing:
- TestAccFWFirewallV1_router_update
- TestAccFWFirewallV1_router_remove

FW instance is in `PENDING_CREATE` status, when test case try to update it (add/remove routers). These test cases have same point, creating new router and assicating router to fw, now we create router without external gateway in fw test cases:

```bash
resource "openstack_networking_router_v2" "router_1" {
  name = "router_1"
  admin_state_up = "true"
}

resource "openstack_fw_policy_v1" "policy_1" {
  name = "policy_1"
}

resource "openstack_fw_firewall_v1" "fw_1" {
  name = "firewall_1"
  description = "firewall router test"
  policy_id = "${openstack_fw_policy_v1.policy_1.id}"
  associated_routers = ["${openstack_networking_router_v2.router_1.id}"]
}
```

I am not familiar with FWaaS, not sure whether we should create router with `external_network_id` to make FW instance enabled?

Error log:
```bash
2018-06-25 11:15:21.910466 | ubuntu-xenial | --- FAIL: TestAccFWFirewallV1_router_remove (1227.78s)
2018-06-25 11:15:21.910567 | ubuntu-xenial | 	testing.go:518: Step 1 error: Error applying: 1 error(s) occurred:
2018-06-25 11:15:21.910607 | ubuntu-xenial |
2018-06-25 11:15:21.910695 | ubuntu-xenial | 		* openstack_fw_firewall_v1.fw_1: 1 error(s) occurred:
2018-06-25 11:15:21.910717 | ubuntu-xenial |
2018-06-25 11:15:21.910917 | ubuntu-xenial | 		* openstack_fw_firewall_v1.fw_1: Expected HTTP response code [200] when accessing [PUT http://192.168.0.211:9696/v2.0/fw/firewalls/06ed6aff-2583-46f4-a575-ef2f86000e6c], but got 409 instead
2018-06-25 11:15:21.911138 | ubuntu-xenial | 		{"NeutronError": {"message": "Operation cannot be performed since associated firewall 06ed6aff-2583-46f4-a575-ef2f86000e6c is in PENDING_CREATE.", "type": "FirewallInPendingState", "detail": ""}}
2018-06-25 11:15:21.911200 | ubuntu-xenial | === RUN   TestAccFWPolicyV1_basic
```

**Comment by jtopjian** [comment]
@kiwik Ah, interesting. 409's are a common scenario with Neutron-based resources and we have a standard way of handling them like this: https://github.com/terraform-providers/terraform-provider-openstack/blob/cc222c2b726e9ac07251b498f823b0755667d359/openstack/resource_openstack_lb_monitor_v1.go#L278-L283

I'll modify the firewall resource to account for this.

**Comment by jtopjian** [comment]
@kiwik I can confirm that this is an issue with the FWaaS service itself.

What's happening is the firewall is never being fully created -- it's always stuck at `PENDING_CREATE`. This happens until Terraform reaches a timeout which it'll then move on to the next step. Since the firewall is still in `PENDING_CREATE`, the next step fails.

These tests pass for me in a Mitaka environment but I'm able to reproduce the issue in Queens. I've followed these instructions, but it's still not working: https://docs.openstack.org/neutron/latest/admin/fwaas-v1-scenario.html

I suppose we either need to figure out why this isn't working (a FWaaS bug?) or restrict fwaas tests to only be done in Mitaka.

**Comment by kiwik** [comment]
@jtopjian good catch, OpenLab run fwaas test against latest master devstack and OpenStack, I think that is why your Mitaka env can pass, but OpenLab failing, and I tend to this is FwaaS bug, we build devstack config like this: 

```bash
ENABLED_SERVICES=c-api,c-bak,c-sch,c-vol,ceilometer-acentral,ceilometer-acompute,ceilometer-alarm-evaluator,ceilometer-alarm-notifier,ceilometer-anotification,ceilometer-api,ceilometer-collector,cinder,dstat,etcd3,g-api,g-reg,key,mysql,n-api,n-api-meta,n-cauth,n-cond,n-cpu,n-novnc,n-obj,n-sch,peakmem_tracker,placement-api,q-agt,q-dhcp,q-l3,q-meta,q-metering,q-svc,rabbit,s-account,s-container,s-object,s-proxy
enable_service q-fwaas-v1
enable_plugin neutron-fwaas https://git.openstack.org/openstack/neutron-fwaas
```

See details in
http://logs.openlabtesting.org/logs/44/344/b9c7228b7503c138fc75bb12cb95dd2d78688d37/recheck-fwaas/terraform-provider-openstack-acceptance-test-fwaas/213f727/logs/local.conf.txt.gz

**Comment by liu-sheng** [comment]
recheck fwaas

**Comment by kiwik** [comment]
Hi @jtopjian , I can comfirm this is devstack fwaas plugin issue, that cause some fwaas options lack in neutron config file, I add these options into my local environment, fwaas instance will become ACTIVE status. The related bug in OpenStack community side is https://review.openstack.org/#/c/508100/

**Comment by jtopjian** [comment]
@kiwik You are a hero!

Do you think we can go ahead and merge this and fix the `fwaas` check later? Whether or not this is merged, the test still fails, so I'm leaning on merging this.

**Comment by kiwik** [comment]
@jtopjian +1 for merging this PR first :-)

**Pull request merged**
