### PR TITLE
Networking V2: add QoS Policy resource

### PR DESCRIPTION
**Pull request by ozerovandrei**
Implement "openstack_networking_qos_policy_v2" resource with acceptance
tests and website documentation.

For #760

### CODE REVIEW

**Comment by bzhaoopenstack** [comment]
recheck

**Comment by ozerovandrei** [comment]
I forgot to add the `testAccPreCheckAdminOnly`:

```
2019-06-14 11:19:04.920235 | ubuntu-xenial | X-Openstack-Request-Id: req-046ac8d3-8e56-4b43-811d-fd35b1f6ce80
2019-06-14 11:19:04.920504 | ubuntu-xenial | 2019/06/14 11:19:04 [DEBUG] OpenStack Response Body: {
2019-06-14 11:19:04.920621 | ubuntu-xenial |   "NeutronError": {
2019-06-14 11:19:04.920777 | ubuntu-xenial |     "detail": "",
2019-06-14 11:19:04.921062 | ubuntu-xenial |     "message": "rule:create_policy is disallowed by policy",
2019-06-14 11:19:04.921242 | ubuntu-xenial |     "type": "PolicyNotAuthorized"
2019-06-14 11:19:04.921288 | ubuntu-xenial |   }
2019-06-14 11:19:04.921372 | ubuntu-xenial | }
```

**Comment by ozerovandrei** [comment]
recheck

**Comment by jtopjian** [comment]
@ozerovandrei The amount of vendor files is a little strange. Did you run the following?

```shell
go get github.com/gophercloud/gophercloud
go mod tidy
go mod vendor
```

**Comment by ozerovandrei** [comment]
@jtopjian I did the following:
```
go get -u github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/qos/policies@master
go mod tidy
go mod vendor
```

**Comment by jtopjian** [comment]
I think it might be the `-u` causing the diff?

Omitting the `-u` should only update the package you specify. `-u` will do a chain of updates.

**Comment by ozerovandrei** [comment]
@jtopjian you're right!

Cleaned it up in the following PR: #774

**Pull request closed without merging**
