### PR TITLE
DBv1: instance cleanup

### PR DESCRIPTION
**Pull request by jtopjian**
@eugenetaranov When you have some time, can you look this over and test it? Functionality should be the same.

I had to remove the Import support, though, because it's not currently working and there wasn't an import test included initially.

### CODE REVIEW

**Comment by jtopjian** [comment]
recheck trove

**Comment by jtopjian** [comment]
recheck trove

**Comment by jtopjian** [comment]
recheck trove

**Comment by liu-sheng** [comment]
recheck trove

**Comment by animationzl** [comment]
recheck trove

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck trove

**Comment by animationzl** [comment]
recheck trove

**Comment by jtopjian** [comment]
recheck trove

**Comment by jtopjian** [comment]
@eugenetaranov Thank you for testing this :smile:

**Pull request merged**
