### PR TITLE
Lbaas v2: Properly handle 404 error on status checks

### LINKED ISSUE #882: Lbaas v2: Neutron status checks race conditions on delete
### Affected Resource(s)
Please list the resources as a list, for example:
- openstack_lb_listener_v2

### Terraform Configuration Files
```hcl
resource "openstack_lb_loadbalancer_v2" "a4b6b60d5fa2941699f21c5e4ee916aab" {
  name          = "test"
  vip_subnet_id = "ddbbd2c3-fa7d-4d44-9987-50562cc62694"
}

resource "openstack_lb_listener_v2" "http" {
  name            = "http"
  protocol        = "HTTP"
  protocol_port   = 80
  loadbalancer_id = "${openstack_lb_loadbalancer_v2.a4b6b60d5fa2941699f21c5e4ee916aab.id}"
}
```

### Debug Output

On destroy terraform can return the wrong result:

```
Error: Error waiting for openstack_lb_listener_v2 cb1f75ef-a744-40c0-8899-2f389067fc4a to become DELETED: Unable to get statuses from the Load Balancer 8b8c1de6-ffe8-4fd7-8099-525d54932abe statuses tree: Resource not found
```

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior

`gophercloud.ErrDefault404` err type has to be handled.

### Actual Behavior

A regular error is returned instead.

### PR DESCRIPTION
**Pull request by kayrus**
Resolves #882

### CODE REVIEW

**Comment by kayrus** [comment]
recheck lbaas

**Comment by ozerovandrei** [comment]
recheck lbaas

**Comment by kayrus** [comment]
recheck lbaas

**Comment by kayrus** [comment]
@ozerovandrei ready for review

**Pull request merged**
