### PR TITLE
openstack_lb_pool_v2 - Make 'cookie_name' optional. 

### LINKED ISSUE #57: Creating lbaas pool with persistent type SOURCE_IP
### Terraform Version
Terraform v0.9.11

### Affected Resource(s)
- openstack_lb_pool_v2 

### Terraform Configuration Files
```hcl

# LOAD BALANCER
resource "openstack_lb_loadbalancer_v2" "lb_1" {
	name = "TEST_LB"
	# Your Private network sub-net ID {source openrc; openstack network list}
  vip_subnet_id = "265fcfa3-eb18-4e2d-9e29-2f8f4506106f"
}

#LISTENER 1
resource "openstack_lb_listener_v2" "listener_1" {
  name = "listener01"
  description = "This is the listener description"
  protocol        = "HTTP"
  protocol_port   = 8080
  loadbalancer_id = "${ openstack_lb_loadbalancer_v2.lb_1.id }"
  region = "${var.region}"
}

#LISTENER 2
resource "openstack_lb_listener_v2" "listener_2" {
  name = "listener02"
  description = "This is the listener 2 description"
  protocol        = "HTTP"
  protocol_port   = 8081
  loadbalancer_id = "${ openstack_lb_loadbalancer_v2.lb_1.id }"
  region = "${var.region}"
}

#POOL 1
resource "openstack_lb_pool_v2" "pool_1" {
  name = "pool01"
  protocol    = "HTTP"
  lb_method   = "ROUND_ROBIN"
  listener_id = "${ openstack_lb_listener_v2.listener_1.id }"
  # loadbalancer_id = "${ openstack_lb_loadbalancer_v2.lb_1.id }"
  region = "${var.region}"

  persistence {
    type        = "APP_COOKIE"
    cookie_name = "Cookie_test"
  }
}

#POOL 2
resource "openstack_lb_pool_v2" "pool_2" {
  name = "pool02"
  protocol    = "HTTP"
  lb_method   = "ROUND_ROBIN"
  listener_id = "${ openstack_lb_listener_v2.listener_2.id }"
  # loadbalancer_id = "${ openstack_lb_loadbalancer_v2.lb_1.id }"
  region = "${var.region}"

  persistence {
    type        = "SOURCE_IP"
    cookie_name = "null"
  }
}
```

### Debug Output

https://gist.github.com/sirajudheenam/a5d80dba18bfde7c4c58a8bf0e744e38

### Panic Output
N/A

### Expected Behavior
It should have created the load balancer pool with persistent type as SOURCE_IP without the need of cookie_name. 
Because I can create with this neutron cli command the same load balancer pool without cookie_name.
`neutron lbaas-pool-create --name "LB_HTTP_POOL" --lb-algorithm ROUND_ROBIN --loadbalancer a55a3fe0-3160-4a24-a7aa-e7487173fe73 --protocol HTTP --session-persistence type=SOURCE_IP`

### Actual Behavior
It produced error saying that `openstack_lb_pool_v2.pool_2: Error creating OpenStack LBaaSV2 pool: Invalid request due to incorrect syntax or missing required parameters.`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
OpenStack Version: Mitaka

### References
None.

### PR DESCRIPTION
**Pull request by fatmcgav**
Need to work on validation, as 'ValidateFunc' can\'t access other schema values...

Fixes #57

### CODE REVIEW

**Comment by jtopjian** [comment]
> Either way, it's a bug, as cookie_name should only be required if type is set to to HTTP_COOKIE or APP_COOKIE.

Yeah, this is kind of common. You'll have to validate the correct combination in the Create and Update functions. Unfortunately this means that that an error won't be displayed when doing `plan`, but that's a Terraform limitation at this time.

**Comment by fatmcgav** [comment]
Yeh, had the same convo with radeksimko. 
The 2 options were validate in C+U actions, or leave the action to fail on the API. 

However with the known 'wooly' error messages returned by Gophercloud, probably makes more sense to fail first in Terraform...

**Comment by jtopjian** [comment]
If you can get it to work, definitely. But if not, asking users to check `OS_DEBUG` should be OK. It's not the _best_, but I think it's manageable for now.

**Comment by fatmcgav** [comment]
@jtopjian I've reworked this so that `cookie_name` is only required when `type = APP_COOKIE`. Also updated the documentation.

Feel free to give it a final test and once you're happy I'll merge it in :)

**Comment by jtopjian** [comment]
This works and I see the benefit of not setting the cookie name, but I think we should error out if there's an incorrect combination. I feel like doing otherwise would be lying to the user about what's going on. It might cause confusion if the user is relying on what the Terraform configuration says but wasn't reflected in the actual created resource.

What do you think?

**Comment by fatmcgav** [comment]
@jtopjian I thought the validation I added in the [Create](https://github.com/terraform-providers/terraform-provider-openstack/pull/58/files#diff-30f5cf81c9148a921249dfd1809e0069R153) call should error out if there's an invalid combination. 

Or are there some different combinations that should be validated aswell?

**Pull request merged**
