### PR TITLE
openstack_db_instance_v1 support for database and user

### PR DESCRIPTION
**Pull request by eugenetaranov**
This PR adds support for database and user paramaters in openstack_db_instance resource and addresses https://github.com/terraform-providers/terraform-provider-openstack/issues/141

This is a contribution from [Ribose Inc.](https://www.ribose.com)

### CODE REVIEW

**Comment by jtopjian** [comment]
@eugenetaranov Thank you for working on this. However, it would be best if this was broken out into two new resources: `openstack_db_database_v1` and `openstack_db_user_v1`. Let me know if you have any questions :)

**Comment by jtopjian** [comment]
Actually, I take that back. It turns out the DBv1 instance _does_ have the ability to create databases and users... as odd as it may be.

I'll run this through some tests and get back to you.

**Comment by eugenetaranov** [comment]
@jtopjian exactly :) I am going to send you another PR soon for standalone user and db resources.

**Comment by eugenetaranov** [comment]
@jtopjian thank you, please review

**Comment by jtopjian** [comment]
@eugenetaranov Looks good! Thank you very much.

Do you plan on doing any further work to this resource? I'd like to get a new release out this week but can wait until this resource is finished entirely.

**Comment by eugenetaranov** [comment]
@jtopjian thank you! Yes, there is a minor change needs to be added for configuration groups to work, will send it asap then.

**Pull request merged**
