### PR TITLE
Remove mitaka check job as ubuntu-trusty is EOL(fix-go-sum)

### PR DESCRIPTION
**Pull request by bzhaoopenstack**
fix-go-sum branch needs to update the zuul configuration

### CODE REVIEW

**Comment by ozerovandrei** [comment]
@bzhaoopenstack looks good but why create 3 duplicate PRs? Were they created by mistake?
#965, #966, #967.

**Comment by bzhaoopenstack** [comment]
@ozerovandrei No, I create those PRs for multiple branches, as each branch has a mitaka test job in zuul config. ;-)

**Comment by bzhaoopenstack** [comment]
And openlab zuul will load terraform providers to check whether it contains a ubuntu-trusty zuul configuration, and here our repo(terraforms-providers) doesn't have a protect branch. So the zuul will check all branches. Also the old config for mitaka need to be updated. ;-)

**Comment by ozerovandrei** [comment]
@bzhaoopenstack I see.
Are they ready to be merged then?

**Comment by ozerovandrei** [comment]
@bzhaoopenstack I see.
Are they ready to be merged then?

**Comment by bzhaoopenstack** [comment]
Yeah, all of them are ready. Thanks. So sorry for late

**Pull request merged**
