### PR TITLE
Internal: Networking V2 Router Route cleanup

### PR DESCRIPTION
**Pull request by ozerovandrei**
Cleanup messages and variables definition for the
openstack_networking_router_route_v2 resource.

For #456

### CODE REVIEW

**Comment by ozerovandrei** [comment]
recheck

**Comment by jtopjian** [comment]
I think you can still use `CheckDeleted` where the 404 checks are being done.

Either way, pending tests passing, this LGTM.

**Comment by ozerovandrei** [comment]
There is an error

```
2019-04-25 10:06:19.724883 | ubuntu-xenial | 2019/04/25 10:06:19 [DEBUG] Retrieved openstack_networking_router_interface_v2 65147063-330a-4185-a86f-2e99c324091c: &ports.Port{ID:"65147063-330a-4185-a86f-2e99c324091c", NetworkID:"547138f3-3d26-4bb9-a59e-3fb8b95637b7", Name:"port_2", Description:"", AdminStateUp:true, Status:"DOWN", MACAddress:"fa:16:3e:01:83:9e", FixedIPs:[]ports.IP{ports.IP{SubnetID:"2006224a-cf92-4d37-84e0-857529c9ab33", IPAddress:"192.168.200.1"}}, TenantID:"632393dc55fc47598f6424068673f919", ProjectID:"632393dc55fc47598f6424068673f919", DeviceOwner:"network:router_interface", SecurityGroups:[]string{"8205a7c6-035e-4ffa-82ff-5a757111a731"}, DeviceID:"d2d3919e-6f02-4b36-b2f1-3fe8c4f9fef6", AllowedAddressPairs:[]ports.AddressPair{}, Tags:[]string{}}
2019-04-25 10:06:19.747712 | ubuntu-xenial | 2019/04/25 10:06:19 [DEBUG] OpenStack Response Code: 404
2019-04-25 10:06:19.748282 | ubuntu-xenial | 2019/04/25 10:06:19 [DEBUG] OpenStack Response Headers:
2019-04-25 10:06:19.748348 | ubuntu-xenial | Content-Length: 103
2019-04-25 10:06:19.748659 | ubuntu-xenial | Content-Type: application/json
2019-04-25 10:06:19.748739 | ubuntu-xenial | Date: Thu, 25 Apr 2019 10:06:19 GMT
2019-04-25 10:06:19.748851 | ubuntu-xenial | X-Openstack-Request-Id: req-d999d707-103f-4eb1-b3f1-ee7759703622
2019-04-25 10:06:19.748949 | ubuntu-xenial | 2019/04/25 10:06:19 [DEBUG] OpenStack Response Body: {
2019-04-25 10:06:19.748997 | ubuntu-xenial |   "NeutronError": {
2019-04-25 10:06:19.749042 | ubuntu-xenial |     "detail": "",
2019-04-25 10:06:19.749130 | ubuntu-xenial |     "message": "Router None could not be found",
2019-04-25 10:06:19.749196 | ubuntu-xenial |     "type": "RouterNotFound"
2019-04-25 10:06:19.749221 | ubuntu-xenial |   }
2019-04-25 10:06:19.749243 | ubuntu-xenial | }
```

It is happening because I'm using `d.Id()` as a parameter for the `routers.Update()` istead of locked `routerID` variable.

**Comment by ozerovandrei** [comment]
@jtopjian test should pass now as it works on my testing environment (just turned it back from the dead right into stein release).

**Comment by ozerovandrei** [comment]
Oh well, there is some issue with the import:
```
2019-04-28 12:32:18.357829 | ubuntu-xenial | --- FAIL: TestAccNetworkingV2RouterRoute_importBasic (69.38s)
2019-04-28 12:32:18.358011 | ubuntu-xenial |     testing.go:538: Step 1 error: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.
2019-04-28 12:32:18.358040 | ubuntu-xenial |
2019-04-28 12:32:18.358066 | ubuntu-xenial |         (map[string]string) {
2019-04-28 12:32:18.358080 | ubuntu-xenial |         }
2019-04-28 12:32:18.358093 | ubuntu-xenial |
2019-04-28 12:32:18.358106 | ubuntu-xenial |
2019-04-28 12:32:18.358133 | ubuntu-xenial |         (map[string]string) (len=1) {
2019-04-28 12:32:18.358190 | ubuntu-xenial |          (string) (len=9) "router_id": (string) (len=36) "6c16e513-8127-4c1a-8d82-a2fca34d2bcb"
2019-04-28 12:32:18.358205 | ubuntu-xenial |         }
2019-04-28 12:32:18.358218 | ubuntu-xenial |
```

**Pull request merged**
