### PR TITLE
[DNM] Testing v0.12 Compatibility

### PR DESCRIPTION
**Pull request by jtopjian**
govendor fetch github.com/hashicorp/terraform/...@c753df6a933ef25197101664b1d7cbb5d115701d
govendor fetch github.com/hashicorp/hcl2/...
govendor fetch github.com/golang/protobuf/...@v1.2.0
govendor fetch github.com/zclconf/go-cty/...
govendor fetch github.com/hashicorp/go-plugin/...
govendor fetch github.com/hashicorp/go-version/...

### CODE REVIEW

**Comment by jtopjian** [comment]
I'm not sure why Travis is flagging an error about locally modified vendor files. That's something to sort out later - I'm only concerned with acceptance tests at this time.

**Comment by jtopjian** [comment]
It looks like there's a core bug where the indices for `TypeSet` are using a 0-based index rather than the hash. This bug is causing most (if not all) of the failures currently seen in testing.

The results at the moment are:

PASS: 86
FAIL: 14

This is only counting what is being run in OpenLab - we'll need to do some manual test runs for the resources which are being skipped. I was able to do this when we did the Gophercloud vendor sync - just have to find the right environments which support the services :)

**Comment by jtopjian** [comment]
recheck

**Comment by jtopjian** [comment]
recheck

**Comment by jtopjian** [comment]
recheck

**Comment by jtopjian** [comment]
recheck

**Comment by kiwik** [comment]
recheck

**Comment by jtopjian** [comment]
recheck designate

**Comment by jtopjian** [comment]
reched lbaas

**Comment by jtopjian** [comment]
recheck lbaas

**Comment by jtopjian** [comment]
I also tested all of the admin-only tests and they passed, too. I think we should be good to go for v0.12 compatibility. 😄

**Comment by jtopjian** [comment]
recheck

**Comment by h00130372** [comment]
recheck

**Comment by h00130372** [comment]
recheck designate

**Comment by jtopjian** [comment]
recheck

**Comment by jtopjian** [comment]
recheck

**Comment by h00130372** [comment]
recheck

**Comment by jtopjian** [comment]
hmm... that failing test is passing outside of openlab.

**Comment by jtopjian** [comment]
recheck

**Comment by jtopjian** [comment]
recheck

**Comment by h00130372** [comment]
recheck

**Comment by kiwik** [comment]
recheck

**Comment by jtopjian** [comment]
recheck

**Pull request closed without merging**
